on:
  release:
    types: [published, released, prereleased, created, edited]
  push:
    tags:
      - v*

name: Publish release
jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-18.04, macos-10.15]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Install build tools
        if: ${{ matrix.os == 'ubuntu-18.04' }}
        run: |
          sudo apt-get update; DEBIAN_FRONTEND="noninteractive" sudo apt-get -y install build-essential curl tzdata
          sudo apt install -y libssl-dev pkg-config
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release
      - name : Prepare release asset
        run: .github/scripts/package_release.sh
      - name: Upload release asset
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          hub release edit -m "" -a drg*.tar.gz ${GITHUB_REF/refs\/tags\//}
